server.port=8084

spring.application.name=search-service

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.service-name=search-service

management.endpoints.web.exposure.include=*

resilience4j.circuitbreaker.instances.tweetService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.tweetService.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.tweetService.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.tweetService.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration;