pipeline {
    agent any
    
    environment {
        NODE_ENV = 'development'
        NG_CLI_ANALYTICS = 'false'
        CI='false'
    }
    
    stages {  
        stage('Install') {
            steps {
                echo 'Installing dependencies...'               
                bat 'npm install --force'
            }
        }         
        
       stage('Frontend - SonarQube Analysis'){
            steps {
                echo 'Performing SonarQube static code analysis...'
                bat 'npm run sonar'
            }
        }           
    }
    
    post {        
        success {
            echo 'All stages passed! Ready for deployment.'
        }
        failure {
            echo ' Pipeline failed. Check logs for issues.'           
        }
    }
}
