sonar.host.url=http://cvwjeemys11:9000
sonar.login=admin
sonar.token=squ_274ec94afd337954a94f4bbd2273fcfb58edc916
#project key and project name should be batchname-groupno-projectname-frontend
sonar.projectKey=Dec25-DSE1-Java-Angular-A-Frontend-1-Twitter    
sonar.projectName=Dec25-DSE1-Java-Angular-A-Frontend-1-Twitter
sonar.sources=src
sonar.exclusions=**/node_modules/**