spring.application.name=followers-service

# Server Port
server.port=8085

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/twitter_follow_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Format SQL in console
spring.jpa.properties.hibernate.format_sql=true

# Logging Level
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

# Swagger UI Path (optional)
springdoc.swagger-ui.path=/swagger-ui.html

#consul configurations
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true

spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true


